services:
  app:
    container_name: trng-webservice
    image: teriyakigod/trng-webservice:latest
    command: ./start-server.sh
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - teriyaki_network

networks:
  teriyaki_network:
    driver: bridge
    external: true
