services:
  db:
    container_name: trng-db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    # networks:
    #   - teriyaki_network

  app:
    container_name: trng-app
    build: .
    command: ./start-server.sh
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    # networks:
    #   - teriyaki_network

    # networks:
    #   teriyaki_network:
    #     driver: bridge
    #     external: true
