name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Log in to GitHub Container Registry
      run: docker login ghcr.io -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trng-webservice:latest

    - name: Tag Docker image for Docker Hub
      run: docker tag trng-webservice:latest teriyakigod/trng-webservice:latest

    - name: Tag Docker image for GitHub Container Registry
      run: docker tag trng-webservice:latest ghcr.io/${{ github.repository }}/trng-webservice:latest

    - name: Push Docker image to Docker Hub
      run: docker push teriyakigod/trng-webservice:latest

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/trng-webservice:latest
