name: Build docker image and push to registries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Tag Docker image for Docker Hub
      run: docker tag my-image-name:latest your_dockerhub_username/your_image_name:latest

    - name: Tag Docker image for GitHub Container Registry
      run: docker tag my-image-name:latest ghcr.io/${{ github.repository }}/your_image_name:latest

    - name: Push Docker image to Docker Hub
      run: docker push your_dockerhub_username/your_image_name:latest

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/your_image_name:latest
