services:
  db:
    container_name: trng-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "8002:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - teriyaki_network
  trng:
    container_name: trng-webservice
    build: .
    command: ./start-server.sh
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - teriyaki_network

networks:
  teriyaki_network:
    driver: bridge
    external: true
