openapi: 3.0.3
info:
  title: TRNG-WEB-API
  version: 1.0.0
  description: Random numbers for everyone!
paths:
  /api/rand/bytes:
    get:
      operationId: bytes_retrieve
      tags:
      - bytes
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/coin:
    get:
      operationId: coin_retrieve
      tags:
      - coin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/dice:
    get:
      operationId: dice_retrieve
      tags:
      - dice
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/float:
    get:
      operationId: float_retrieve
      tags:
      - float
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/int:
    get:
      operationId: int_retrieve
      tags:
      - int
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/lotto:
    get:
      operationId: lotto_retrieve
      tags:
      - lotto
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/sequence:
    get:
      operationId: sequence_retrieve
      tags:
      - sequence
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/rand/string:
    get:
      operationId: string_retrieve
      tags:
      - string
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
